feature 评论系统

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,8 +50,8 @@ jobs:
         run: |
           pnpm run build
           scp -i ~/.ssh/id_rsa -P ${{ secrets.SERVER_PORT }} -r .vitepress/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:/opt/www/doc-v3/
-            if [ $? -ne 0 ]; then
-              echo "Upload failed"
-              exit 1
-            fi
-            echo "Upload successful"
+          if [ $? -ne 0 ]; then
+            echo "Upload failed"
+            exit 1
+          fi
+          echo "Upload successful"
